# https://www.appveyor.com/docs/appveyor-yml/

# Test against these versions of Node.js.
skip_branch_with_pr: true

branches:
  only:
    - master
    - /^greenkeeper/.*$/

environment:
  MOCHA_REPORTER: "mocha-appveyor-reporter"
  matrix:
    - EMBER_TRY_SCENARIO: test-release
    - EMBER_TRY_SCENARIO: build-release

# Install scripts. (runs after repo cloning)
install:
  - appveyor-retry npm i -g npm@^4
  - appveyor-retry npm install mocha-appveyor-reporter # must be installed locally.

# Post-install test scripts.
test_script:
  - cmd: npm install --no-package-lock
  - cmd: node_modules/.bin/ember try:one %EMBER_TRY_SCENARIO%

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
