# Start ExplorViz Backend in version dev
# Monitored applications can be connected

# go to http://localhost:8090 to open the ExplorViz Frontend

# Environment Variables are based on the 
# properties file of each service, e.g, 
# https://github.com/ExplorViz/explorviz-backend/blob/dev-1/user-service/src/main/resources/explorviz.properties

version: "3.3"
services:

  ### ExplorViz Services ###

  user-service:
    image: explorviz/explorviz-backend-user-service:dev
    container_name: explorviz-backend-user-service
    expose:
      - "8082"
    depends_on:
      - mongo-user
      - kafka
      - traefik
    environment:
      - MONGO_HOST=mongo-user
      - EXCHANGE_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    labels:
      - "traefik.enable=true"
      - "traefik.port=8082"
      - "traefik.http.routers.user-service.rule=PathPrefix(`/v1/tokens`) || PathPrefix(`/v1/users`) || PathPrefix(`/v1/roles`) || PathPrefix(`/v1/userbatch`)"

  settings-service:
    image: explorviz/explorviz-backend-settings-service:dev
    container_name: explorviz-backend-settings-service
    expose:
      - "8087"
    depends_on:
      - mongo-settings
      - kafka
      - traefik
    environment:
      - MONGO_HOST=mongo-settings
      - EXCHANGE_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    labels:
      - "traefik.enable=true"
      - "traefik.port=8087"
      - "traefik.http.routers.settings-service.rule=PathPrefix(`/v1/settings`) || PathPrefix(`/v1/preferences`)"

  landscape-service:
    image: explorviz/explorviz-backend-landscape-service:dev
    container_name: explorviz-backend-landscape-service
    ports:
      - "10135:10135"
    expose:
      - "10135"
    depends_on:
      - kafka
    environment:
      - EXCHANGE_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EXCHANGE_KAFKA_TOPIC_NAME=landscape-update

  broadcast-service:
    image: explorviz/explorviz-backend-broadcast-service:dev
    container_name: explorviz-backend-broadcast-service
    expose:
      - "8081"
    depends_on:
      - kafka
      - traefik
    environment:
      - EXCHANGE_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EXCHANGE_KAFKA_TOPIC_NAME=landscape-update
    labels:
      - "traefik.enable=true"
      - "traefik.port=8081"
      - "traefik.http.routers.broadcast-service.rule=PathPrefix(`/v1/landscapes/broadcast`)"
      - "traefik.http.routers.broadcast-service.priority=200"

  history-service:
    image: explorviz/explorviz-backend-history-service:dev
    container_name: explorviz-backend-history-service
    expose:
      - "8086"
    depends_on:
      - mongo-history
      - kafka
      - traefik
    environment:
      - MONGO_HOST=mongo-history
      - EXCHANGE_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EXCHANGE_KAFKA_TOPIC_NAME=landscape-update
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.history-service.rule=PathPrefix(`/v1/landscapes`) || PathPrefix(`/v1/timestamps`) "
      - "traefik.port=8086"

  analysis-service:
    image: explorviz/explorviz-backend-analysis-service:dev
    container_name: explorviz-backend-analysis-service
    ports:
      - "10133:10133"

  discovery-service:
    image: explorviz/explorviz-backend-discovery-service:dev
    container_name: explorviz-backend-discovery-service
    ports:
      - "8083:8083"
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.port=8083"
      - "traefik.http.routers.discovery-service.rule=PathPrefix(`/v1/agents`)"

  ### Software Stack ###

  traefik:
    image: "traefik:v2.0.1"
    container_name: "explorviz-reverse-proxy"
    command:
      - "--entrypoints.web.address=:8080"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    expose:
      - "2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


  mongo-user:
    image: mongo
    container_name: explorviz-backend-user-mongo
    command: mongod --port 27017
    volumes:
       - explorviz-user-mongo-data:/data/db
       - explorviz-user-mongo-configdb:/data/configdb
    expose:
      - "27017"

  mongo-history:
    image: mongo
    container_name: explorviz-landscape-mongo
    command: mongod --port 27018
    volumes:
       - explorviz-landscape-mongo-data:/data/db
       - explorviz-landscape-mongo-configdb:/data/configdb
    expose:
      - "27018"

  mongo-settings:
    image: mongo
    container_name: explorviz-settings-mongo
    command: mongod --port 27019
    ports:
      - 27019:27019
    volumes:
      - explorviz-settings-mongo-data:/data/db
      - explorviz-settings-mongo-configdb:/data/configdb

volumes:
  explorviz-user-mongo-data:
  explorviz-user-mongo-configdb:
  explorviz-landscape-mongo-data:
  explorviz-landscape-mongo-configdb:
  explorviz-settings-mongo-data:
  explorviz-settings-mongo-configdb:
